"""serviceorders-0.1

Revision ID: 28c753c1f5c3
Revises: 3ef6282447b4
Create Date: 2022-10-28 11:03:13.120967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c753c1f5c3'
down_revision = '3ef6282447b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
