"""auto nullable

Revision ID: 3ef6282447b4
Revises: 9631ba7f32e0
Create Date: 2022-10-23 17:21:03.208213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef6282447b4'
down_revision = '9631ba7f32e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
