"""serviceorders-0.2

Revision ID: 4d92b1bdeca4
Revises: 28c753c1f5c3
Create Date: 2022-10-28 23:21:26.189885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d92b1bdeca4'
down_revision = '28c753c1f5c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
