"""v3

Revision ID: 4f67096154d9
Revises: 5e050563a95b
Create Date: 2022-11-02 13:31:06.890105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f67096154d9'
down_revision = '5e050563a95b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.Integer(), nullable=True),
    sa.Column('datanasc', sa.String(length=255), nullable=True),
    sa.Column('tel', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notefiscal',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('createat', sa.String(length=255), nullable=True),
    sa.Column('clientid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notefiscal')
    op.drop_table('statuses')
    op.drop_table('cliente')
    # ### end Alembic commands ###
