"""v2

Revision ID: 5e050563a95b
Revises: 6a374a8511b9
Create Date: 2022-11-01 09:56:35.882727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e050563a95b'
down_revision = '6a374a8511b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('typeid', sa.Integer(), nullable=True))
    op.drop_column('service_orders', 'typeId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_orders', sa.Column('typeId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('service_orders', 'typeid')
    # ### end Alembic commands ###
