"""serviceorders-0.5

Revision ID: 77c9f2ac4914
Revises: c3fa7b3baa12
Create Date: 2022-10-29 09:48:33.603267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c9f2ac4914'
down_revision = 'c3fa7b3baa12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
