"""subprocess-adjust

Revision ID: 77eda1fcffd5
Revises: 9c3ae2fa090e
Create Date: 2022-11-10 11:38:32.759408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77eda1fcffd5'
down_revision = '9c3ae2fa090e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
