"""serviceorders-0.2

Revision ID: 7ba902d1dbcc
Revises: 4d92b1bdeca4
Create Date: 2022-10-28 23:24:55.772942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba902d1dbcc'
down_revision = '4d92b1bdeca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
