"""pwd2

Revision ID: 9631ba7f32e0
Revises: a50b31bc8555
Create Date: 2022-10-21 13:31:56.769189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9631ba7f32e0'
down_revision = 'a50b31bc8555'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
