"""subprocess

Revision ID: 9c3ae2fa090e
Revises: 4f67096154d9
Create Date: 2022-11-10 11:36:33.220063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3ae2fa090e'
down_revision = '4f67096154d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('subprocess', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'subprocess')
    # ### end Alembic commands ###
