"""pwd-account

Revision ID: a50b31bc8555
Revises: 5a63e5df0ac5
Create Date: 2022-10-21 13:27:27.566687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50b31bc8555'
down_revision = '5a63e5df0ac5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Account', sa.Column('pwd', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Account', 'pwd')
    # ### end Alembic commands ###
