"""serviceorders-0.4

Revision ID: c3fa7b3baa12
Revises: d9e7649ef1b8
Create Date: 2022-10-28 23:44:33.745793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3fa7b3baa12'
down_revision = 'd9e7649ef1b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
