"""serviceorders-0.3

Revision ID: d9e7649ef1b8
Revises: 7ba902d1dbcc
Create Date: 2022-10-28 23:26:35.307048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e7649ef1b8'
down_revision = '7ba902d1dbcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
